uint16 front_pow_lift_hgt       # height command for front pto
uint16 mid_pow_lift_hgt         # height command for middle pto
uint16 rear_pow_lift_hgt        # height command for rear pto
bool front_pow_lift_flt         # Flag to activate front power lifter float
bool mid_pow_lift_flt           # Flag to activate middle power lifter float
bool rear_pow_lift_flt          # Flag to activate rear power lifter float