uint16 steer_ang_magn  # magnitude of steering angle deg
uint16 drv_spd_magn    # magnitude of vehicle speed km/h
uint16 eng_spd         # magnitude of engine speed rpm
bool steer_dir_le      # flag for left steering
bool steer_dir_ri      # flag for right steering
bool drv_dir_fwd       # flag for forward driving
bool drv_dir_bwd       # flag for backward driving
bool front_pto         # flag for front pto
bool rear_pto          # flag for rear pto
bool mission_avail     # flag for mission availability