uint16 steer_ang_magn           # magnitude of actual steering angle
uint16 drv_spd_magn             # magnitude of actual vehicle speed
bool drv_dir_bwd                # flag for backward driving direction
bool drv_dir_fwd                # flag for forward driving direction
bool steer_dir_le               # flag for steer direction left
bool steer_dir_ri               # flag for steer direction right
uint8 steer_st                  # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 drv_st                    # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 eng_st                    # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 front_pow_lift_lift_st    # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 front_pow_lift_low_st     # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 front_pow_lift_flt_st     # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 front_pto_st              # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 mid_pow_lift_lift_st      # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 mid_pow_lift_low_st       # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 mid_pow_lift_flt_st       # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 rear_pto_st               # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 rear_pow_lift_lift_st     # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 rear_pow_lift_low_st      # 0: OFF; 1: ON; 2: Error; 3: NA
uint8 rear_pow_lift_flt_st      # 0: OFF; 1: ON; 2: Error; 3: NA
